name: Update JSON & Deploy Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write   # checkout & push JSON
  pages: write      # 发布 Pages
  id-token: write   # deploy-pages 需要

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Generate file-list.json
        run: node scripts/generate-file-list.js
      - name: Commit & push JSON if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if ! git diff --quiet blog/post/file-list.json; then
            git add blog/post/file-list.json
            git commit -m "Auto: Update blog/post/file-list.json [skip ci]"
            git push
          fi

  deploy-pages:
    needs: update-json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0       # 确保拿到远端最新提交，包括刚推的 JSON
      - name: Build & Deploy GitHub Pages
        uses: actions/jekyll-build-pages@v1
